### ISSUE TITLE
Columns dont seem to respect values.

### ISSUE THREAD

**Issue by VictorioBerra** [ksylvest/jquery-gridly#17]
When I put columns: 3 I only get one column, when I put columns 10 I get 3 column. 

How do I get the columns to work? Is this all a matter of pixel widths? In the given example columns is set to 12 yet even then the bricks drop to a new line after 6 or so.

**Comment by Karamhaj1995** [comment]
2019 have same problem ........ 3 days of looking for a good library that allows me to do a grid 4 X 3 ... this library is not working well, columns 12 getting 3 10 getting 2
