### ISSUE TITLE
Remove a Brick and Update the Elements

### ISSUE THREAD

**Issue by vitorluis** [ksylvest/jquery-gridly#30]
Hello,

first of all, thank you for this awesome plugin!

So, when i remove a brick from my grid, which method i could call to get the new number of elements in my grid?

Because, when i call:

$('.gridly').gridly('draggingEnded'); // Forcing call the reordered callback

the callback is called passing the old elements, with the element i removed before.

Anything i can do?

**Comment by ksylvest** [comment]
From **sample.css**:

    $(document).on("click", ".gridly .delete", function(event) {
      var $this;
      event.preventDefault();
      event.stopPropagation();
      $this = $(this);
      $this.closest('.brick').remove();
      return $('.gridly').gridly('layout');
    });

Then to get a count you can use the jQuery length methods: 

    %('.gridly .brick').length
