### ISSUE TITLE
How to reorder column-wise

### ISSUE THREAD

**Issue by anoopsinghbayes** [ksylvest/jquery-gridly#35]
Hi Thanks for the great plugin ,
Currently the grid items reorder row wise that is when i select an item in first row and put in second row
the reorder is row wise ,can any one suggest how can i have the reorder to happen column wise

**Comment by ksylvest** [comment]
@anoopsinghbayes Right now this feature isn't supported. Your best bet is probably to fork the code and start reading through to figure out the changes that would be required. Closing as not an issue
