### ISSUE TITLE
How can I get the element that was repositioned?

### ISSUE THREAD

**Issue by jensljungblad** [ksylvest/jquery-gridly#36]
I would like to access the element that was reordered it in the reordered callback. Currently it seems to only give me all the elements. Is this possible currently?

**Comment by ksylvest** [comment]
Right now I don't think this is possible. One option is to keep track of the elements outside of the reorder call then do the diff after the reordering.

**Comment by jensljungblad** [comment]
Couldn't the element be passed along as a parameter to the callback?

**Comment by ksylvest** [comment]
They could as a second parameter I suppose (right now the first parameter is the full set of elements). I don't have any bandwidth to add this feature though (pull requests are welcome).

**Comment by ksylvest** [comment]
Closing pending pull request.
