### ISSUE TITLE
How to find the order of items in the grid?

### ISSUE THREAD

**Issue by vinayvinay1** [ksylvest/jquery-gridly#41]
Hi,

Even after reordering items using drag and drop, the DIV tags of items are in the same order as were created, as the items use Absolute position to rearrange.

Is there any way to programmatically get the order of items from say left to right in the grid ?

**Comment by ksylvest** [comment]
Per the README (https://github.com/ksylvest/jquery-gridly)  a `reordered` callback can be included as a configuration option that should return the ordered jquery elements.

**Comment by vinayvinay1** [comment]
oops.. i missed it in the readme.!! my bad.  Thanks for pointing it out.
