### ISSUE TITLE
Resizing, but not by clicking

### ISSUE THREAD

**Issue by brainysmurf** [ksylvest/jquery-gridly#42]
I have a gridly-aware block that is divided into three parts, the draggable/clickable portion, and the resize and the edit portion.

![image](https://cloud.githubusercontent.com/assets/859335/8889709/21cb4b4a-3318-11e5-9076-e0ee492e9daa.png)

What I want to know is how to duplicate the functionality of the demo where a click resizes and grid re-calculates. At the moment, on clicking the resize portion, I add the class "large" and sure enough the block resizes, but there is no subsequent adjustment by the other blocks. 

![image](https://cloud.githubusercontent.com/assets/859335/8889718/7b4dbf72-3318-11e5-96a2-3471bf629703.png)

I tried simulating a click (although this is not ideal, since a click would navigate the user to the href) and I also tried calling gridly() on the grid wrapper.

**Comment by brainysmurf** [comment]
I should note that when I physically click on it after the block resizes, the adjustments do happen.

**Comment by ksylvest** [comment]
Here is the sample snippet from the demo:

```javascript
var $this, size;
event.preventDefault();
event.stopPropagation();
$this = $(this);
$this.toggleClass('small');
$this.toggleClass('large');
if ($this.hasClass('small')) {
  size = 140;
}
if ($this.hasClass('large')) {
  size = 300;
}
$this.data('width', size);
$this.data('height', size);
$('.gridly').gridly('layout');
```
