### ISSUE TITLE
Gridly draggable anchor

### ISSUE THREAD

**Issue by jaumard** [ksylvest/jquery-gridly#43]
Hi,

I found your plugin and found it great but I need to have only the header of my div who can allow drag and not the all div. 
Anyway to do this ?

I try to set draggable.selector with css class but not all div was dragged :( only the css class 

Thanks

**Comment by ksylvest** [comment]
This functionality isn't currently supported. PR for it in CoffeeScript would be welcome (otherwise you can prevent mousemove  / touchmove events for the elements you don't want to move).
