### ISSUE TITLE
Added new feature

### ISSUE THREAD

**Issue by eminentcodex** [ksylvest/jquery-gridly#44]
Hi , i have added support for brick selection and calling reordering method for both reordering and select brick event. Allow me commit my changes.

**Comment by ksylvest** [comment]
Hey @eminentcodex 

To add in new functionality please fork and open a pull request:
https://help.github.com/articles/fork-a-repo/

Closing this issue and will review the PR whenever it is opened.

Thanks,

Kevin

**Comment by eminentcodex** [comment]
Thanks
