### ISSUE TITLE
How to disable and enable drag n drop

### ISSUE THREAD

**Issue by muni510** [ksylvest/jquery-gridly#5]
Hello,

can you please guide me disable and enable drag n drop...

kindly help me...

**Comment by filipeximenes** [comment]
Shouldn't this be documented in the project page and in the README?

**Comment by ksylvest** [comment]
@filipeximenes Yeah. A pull request with the documentation would be appreciated.

**Comment by filipeximenes** [comment]
pull request #39

**Comment by ksylvest** [comment]
Awesome! Merged thanks for the help.
