### ISSUE TITLE
Vertical grid

### ISSUE THREAD

**Issue by frostoni** [ksylvest/jquery-gridly#57]
Hi, is there a way to have 2 grids, one which can only be ordered vertically? Something like:
**ABBBB
ABBBB
ABBBB
0BBBB
0BBBB**

Where **A** can only be reordered vertically, **B** is a normal gridly, and **0** is empty space that isn't to be filled with anything, which is ok, i can just put the BBBB sections with a margin-left spacer.

Please halp!

**Comment by ksylvest** [comment]
Have two grid and align them using CSS.

**Comment by frostoni** [comment]
could you please expand on that issue for people who want to make vertical separate gridlys?

despite being in a table to force the grid layout i proposed, the divs keep stacking up right next to each other. Is there a patch in the plugin that would restrain this behaviour?

Terribly sorry to be a bother, I did try to parse your plugin throughout, but i couldn't find a solution...
