### ISSUE TITLE
Jquery version compatibility

### ISSUE THREAD

**Issue by eliysha** [ksylvest/jquery-gridly#59]
Hi,

I would like if this lib will working with jQuery 1.7.1 ?
If not, do you have some recommandations ?

Regards,

**Comment by ksylvest** [comment]
Have you tested with jQuery 1.7.1? What bugs are you seeing? I don't see why it wouldn't.

**Comment by eliysha** [comment]
I tested with jQuery 1.7.1 it doesn't work
Boxes are not draggable

**Comment by ksylvest** [comment]
@eliysha if you upgrade jQuery does it work?

**Comment by eliysha** [comment]
Yes it works with jQuery 2.0.2 used in your example.
I have to use 1.7.1

**Comment by ksylvest** [comment]
@eliysha that version of jQuery is now almost five years old. You should upgrade to 1.12.2 or 2.2.2. Otherwise you can fork and fix.

**Comment by eliysha** [comment]
Yes I know but it doesn't depend on me 
So if I need to fix, on what should I focus my effort ?

**Comment by ksylvest** [comment]
@eliysha no clue.

**Comment by eliysha** [comment]
ok
thank you for answers
