### ISSUE TITLE
who can help to provide a frame explain for source code ?

### ISSUE THREAD

**Issue by dragonQiang** [ksylvest/jquery-gridly#60]
i am a new coder for web. it's hard for me to read the source code.
who have a help document for the source code?
thank you!

my email:a625846910@163.com

**Comment by ksylvest** [comment]
@dragonQiang README.md (https://github.com/ksylvest/jquery-gridly/blob/master/README.md) and http://ksylvest.github.io/jquery-gridly/ both provide documentation on using the project. Best of luck.
