### ISSUE TITLE
Delete button's callback not run correctly on mobile.

### ISSUE THREAD

**Issue by sephirothz87** [ksylvest/jquery-gridly#61]
When click center of delete button, there is no response on mobile mode.

It also happen on my iphone6s.

Only click a little right and above part of the button, click event can be called.

**Comment by repli2dev** [comment]
I am experiencing the same problem. The button is non clickable on mobile (iOS 9.3) and drag event is invoked instead.

**Comment by ksylvest** [comment]
@repli2dev probably an issue with iOS not having the 'click' event. PR would be appreciated (but shouldn't effect the underlying framework - just the demo code).

**Comment by repli2dev** [comment]
@ksylvest I don't think this is "an not having 'click' event" issue as the click handler works elsewhere and also documentation says it is [supported](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html#//apple_ref/doc/uid/TP40006511-SW5).
Will look deeper into this issue soon.

**Comment by repli2dev** [comment]
@ksylvest I have debugged the click event into the library but lost aftewards (as I don't understand the library architecture), so we decided not to waste too much time and switched to another library.

**Comment by teekcode** [comment]
I think the problem still exists in chrome device toolbar. Would it be something from preventDefault?

**Comment by teekcode** [comment]
I bind the element with another event and it should work as except.

$('.gridly').on('click touchstart', '.remove-category', function () {
//TODO
});

More information: [document-click-function-for-touch-device](https://stackoverflow.com/questions/11397028/document-click-function-for-touch-device)
