### ISSUE TITLE
Grid Width

### ISSUE THREAD

**Issue by Ang3ls** [ksylvest/jquery-gridly#64]
how can I set the width of the grid?
And 'possible to set the width also in relation with the width of the page? so that the cells can move to the next line if you end up out the window?

thanks

**Comment by hyj19920418** [comment]
you can use the param of the demo like this:
$('.gridly').gridly({
        base: 60, // px
        gutter: 8, // margin  px
        columns: 12 // width;This is not strictly a wide
    });
you can try it
