### ISSUE TITLE
Using within a hidden div

### ISSUE THREAD

**Issue by SgtWiggidy** [ksylvest/jquery-gridly#66]
Thanks for your wonderful plugin. I was just wondering if there is a way to refresh it. I am using the plugin as part of a page building workflow and initially it is within a hidden div (step 3). When I enable the div, it shows up as a single column and not in a grid fashion.

**Comment by ksylvest** [comment]
@SgtWiggidy try calling the following:

```javascript
$('.gridly').gridly('layout');
```

You can try it out on the demo page by deleting a few bricks in the DOM (or adding) then running.
