### ISSUE TITLE
Is there any way to serialize current state and use it later?

### ISSUE THREAD

**Issue by iPazooki** [ksylvest/jquery-gridly#70]
I want to save the current state and use it later when the user sees the page.

**Comment by Karamhaj1995** [comment]
It's old I know, 
In my situation I decided to this library to create a movable dashboard.
By a button click it saved... 

`

    function saveGrid(griddata) {
        var griddashboard = []
		$.each($('.gridly .brick'), function(a, b){
			griddashboard.push(JSON.stringify({
				"widget": $(b).attr('widget'),
				"top": $(b).css('top'),
				"left": $(b).css('left')
			}));
		});
        localStorage.setItem('griddashboard', JSON.stringify(griddashboard))
    }

`

and to retrieve the position you need to get the data before the database/localstorage

`
		blockwidth = parseInt(($('.gridly').width()/3) - 2)
		blockheight = parseInt(($('.gridly').height()/3) - 10)
		blockcolumns = parseInt(($('.gridly').width()/blockwidth))
		$(".brick").css("width", blockwidth+"px");
		$(".brick").css("height", blockheight+"px");
                 $('.gridly').gridly({
	            base: blockwidth,
	            gutter: 1,
	            columns: blockcolumns
	        });
		if(localStorage.getItem('griddashboard')) {
			$.each(JSON.parse(localStorage.getItem('griddashboard')), function(index, widget){
				widgetGrid = JSON.parse(widget)
				$('.gridly .brick[widget="'+widgetGrid['widget']+'"]').css('top', widgetGrid['top']);
				$('.gridly .brick[widget="'+widgetGrid['widget']+'"]').css('left', widgetGrid['left']);
			});
		}
`
